import { writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const output = new URL('../../admin/deploy/', import.meta.url);
const assetVersion = createHash('sha256').update(await readFile(new URL('assets/site.css', output))).update(await readFile(new URL('assets/site.js', output))).digest('hex').slice(0, 12);
const arrow = '<span aria-hidden="true">↗</span>';
const brand = '<img src="/assets/brand.svg" width="36" height="36" alt=""><span>礼链<small>LILIAN</small></span>';
const button = (text = '预约产品演示', style = 'primary') => `<button class="button ${style}" data-inquiry>${text}${arrow}</button>`;
const picture = (src, alt, cls = '', eager = false) => `<img class="${cls}" src="/assets/${src}.webp" alt="${alt}" loading="${eager ? 'eager' : 'lazy'}" decoding="async" ${eager ? 'fetchpriority="high"' : ''}>`;
const imageButton = (src, alt, cls = '') => `<button class="image-open ${cls}" data-image="/assets/${src}.webp" data-caption="${alt}" aria-label="放大查看：${alt}">${picture(src, alt)}<span class="zoom-mark" aria-hidden="true">↗</span></button>`;
const eyebrow = (en, cn) => `<p class="eyebrow"><span class="tiny-mark" aria-hidden="true"></span>${en}<span class="eyebrow-cn">${cn}</span></p>`;

function leadForm(kind = 'lead', id = 'contact') {
  const partner = kind === 'partner';
  return `<form class="lead-form" data-kind="${kind}" novalidate>
    <div class="form-fields">
      <div class="form-grid">
        <label for="${id}-company">${partner ? '公司 / 团队' : '公司名称'} <span>*</span><input id="${id}-company" name="company" autocomplete="organization" maxlength="100" placeholder="请输入公司或团队名称" required></label>
        <label for="${id}-name">${partner ? '你的姓名 <span>*</span>' : '怎么称呼你'}<input id="${id}-name" name="name" autocomplete="name" maxlength="40" placeholder="方便我们与你联系" ${partner ? 'required' : ''}></label>
        <label for="${id}-phone">手机号码 <span>*</span><input id="${id}-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="20" placeholder="请输入中国大陆手机号" required></label>
        ${partner ? `<label for="${id}-city">意向城市 <span>*</span><input id="${id}-city" name="city" maxlength="60" placeholder="如：浙江省杭州市" required></label>` : `<label for="${id}-solution">感兴趣的方案<select id="${id}-solution" name="solution"><option value="">请选择（选填）</option><option>AIGC素材工作台</option><option>电商履约</option><option>综合解决方案</option><option>定制服务</option></select></label>`}
      </div>
      <label for="${id}-message">${partner ? '客户资源与合作想法' : '想解决什么问题'}<textarea id="${id}-message" name="message" rows="3" maxlength="1000" placeholder="${partner ? '例如：服务的行业、已有客户资源、希望开展合作的方式' : '例如：商品上新频繁，希望批量制作场景图和短视频'}"></textarea></label>
      <div class="honey" aria-hidden="true"><label>请留空<input name="website" tabindex="-1" autocomplete="off"></label></div>
      <label class="consent"><input type="checkbox" name="consent" required><span>我已阅读<a href="/privacy.html" target="_blank" rel="noopener">隐私说明</a>，同意礼链就本次${partner ? '合作申请' : '咨询'}与我联系。</span></label>
      <p class="form-status" role="status" aria-live="polite"></p>
      <button type="submit" class="button primary form-submit">${partner ? '提交合作申请' : '提交需求，预约演示'}${arrow}</button>
      <p class="form-note">${partner ? '申请提交后，我们将联系你沟通。提交申请不代表获得城市授权。' : '信息仅用于本次业务沟通。你也可以不填表，直接扫码联系我们。'}</p>
    </div>
    <div class="form-success" hidden tabindex="-1"><span class="success-icon" aria-hidden="true">✓</span><h3>${partner ? '合作申请已收到' : '需求已收到'}</h3><p>感谢你的关注。我们将根据你留下的联系方式与你沟通。</p><p class="receipt"></p><button type="button" class="button primary" data-wechat>现在扫码联系${arrow}</button><button type="button" class="text-button" data-form-reset>提交另一条${partner ? '申请' : '需求'}</button></div>
  </form>`;
}

function nav(active) {
  const items = [['/', '首页', 'home'], ['/aigc.html', 'AIGC 素材工作台', 'aigc'], ['/solutions.html', '电商解决方案', 'solutions'], ['/partners.html', '城市合伙人', 'partners']];
  return `<a class="skip-link" href="#main">跳到主要内容</a><header class="site-header"><div class="nav-shell"><a class="brand" href="/" aria-label="礼链首页">${brand}</a><nav id="primary-nav" aria-label="主导航">${items.map(([url, label, key]) => `<a href="${url}" ${active === key ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav><div class="nav-actions"><a class="contact-link" href="/contact.html">联系我们</a>${button('预约演示')}<button class="menu-toggle" aria-controls="primary-nav" aria-expanded="false" aria-label="展开导航"><span></span><span></span></button></div></div></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="container footer-top"><div><a class="brand" href="/">${brand}</a><p>让商品内容，成为生意的增长起点。</p><small>AI COMMERCE, MADE PRACTICAL.</small></div><div><h3>产品与服务</h3><a href="/aigc.html">AIGC 素材工作台</a><a href="/solutions.html#fulfillment">电商履约解决方案</a><a href="/solutions.html#services">标准产品与定制服务</a></div><div><h3>一起成长</h3><a href="/partners.html">成为城市合伙人</a><a href="/contact.html">关于礼链</a><button class="text-button" data-wechat>扫码联系</button></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} 杭州礼鲤科技有限公司</span><a href="/privacy.html">隐私说明</a><span>杭州 · 服务全品类电商团队</span></div></footer>`;
}
function dialogs() {
  return `<dialog id="inquiry-dialog" class="form-dialog" aria-labelledby="inquiry-title"><button class="dialog-close" data-close aria-label="关闭预约窗口">×</button><p class="eyebrow">LET’S TALK</p><h2 id="inquiry-title">从你的商品，开始聊起。</h2><p class="dialog-intro">告诉我们你的需求，一起找到适合的产品与落地方式。</p>${leadForm('lead', 'modal')}</dialog>
  <dialog id="wechat-dialog" class="wechat-dialog" aria-labelledby="wechat-title"><button class="dialog-close" data-close aria-label="关闭二维码窗口">×</button><div class="qr-brand">${brand}</div><p class="eyebrow">A CONVERSATION STARTS HERE</p><h2 id="wechat-title">扫码，直接聊聊。</h2><p>使用微信扫一扫，添加礼链业务联系人</p><img class="contact-qr" src="/assets/contact-qr.png" width="324" height="324" alt="礼链业务联系二维码"><p class="small">手机浏览时，可保存二维码后在微信中识别。</p><a class="button secondary" href="/assets/contact-qr.png" download="礼链业务联系二维码.png">保存二维码 ↓</a><p class="small">无需先填写表单，也可以直接联系。</p></dialog>
  <dialog id="media-dialog" class="media-dialog" aria-label="素材预览"><button class="dialog-close" data-close aria-label="关闭素材预览">×</button><div class="media-body"></div><p class="media-caption"></p></dialog>
  <div class="mobile-dock"><button data-wechat>扫码联系</button>${button('预约演示')}</div>`;
}
const sectionHead = (en, cn, title, desc = '') => `<div class="section-head"><div>${eyebrow(en, cn)}<h2>${title}</h2></div>${desc ? `<p>${desc}</p>` : ''}</div>`;
const cta = () => `<section class="end-cta"><div class="container"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>把下一个上新，<br>变成新的开始。</h2></div><div><p>从一个商品、一个场景开始，<br>找到适合你的 AI 电商工作方式。</p>${button()}<button class="text-button" data-wechat>或直接扫码联系 →</button></div></div></section>`;

const home = `
<section class="hero container">
  <div class="hero-copy">${eyebrow('LILIAN · AI COMMERCE', '礼链 AI 电商解决方案')}<h1>好商品，<br>值得<span class="serif-accent">被看见。</span></h1><p class="hero-description">用 AI 把商品变成图片、视频与更多生意机会。<br>从素材生产到电商履约，礼链陪你把每一步落到实处。</p><div class="hero-actions">${button()}<a class="button quiet" href="/aigc.html#showcase"><span class="play-mini" aria-hidden="true">▶</span> 看看素材效果</a></div><div class="hero-footnote"><span class="live-dot"></span>AIGC 素材工作台<span class="divider">/</span>标准产品 + 定制服务</div></div>
  <div class="hero-gallery"><div class="gallery-rule"><span>ONE PRODUCT. MORE POSSIBILITIES.</span><span>01 / 03</span></div><div class="hero-main-image">${picture('scene', '绿色家居服模特场景素材展示', '', true)}<span class="image-label">AI 场景素材</span><div class="hero-image-caption"><span>一款商品，多种表达</span><span>CREATED WITH AI ↗</span></div></div><div class="source-float">${picture('detail', '同款绿色家居服商品细节素材', '', true)}<span>从商品细节出发<span>↗</span></span></div><button class="video-float" data-video="/assets/video-result-web.mp4" data-poster="/assets/video-poster.webp" data-caption="授权参考视频复刻 · 绿色家居服" aria-label="播放绿色家居服视频复刻结果">${picture('video-poster', '绿色家居服视频复刻结果预览', '', true)}<span class="play-circle" aria-hidden="true">▶</span><span class="video-float-caption">延展为视频 <span>PLAY ↗</span></span></button><span class="gallery-index">PRODUCT STORY / 001</span></div>
</section>
<div class="capability-band"><div class="container"><span>让内容生产接上业务</span><span>商品素材管理</span><i>✦</i><span>AI 图片与视频</span><i>✦</i><span>模板与审核归档</span><i>✦</i><span>活动与履约</span></div></div>
<section class="section container" id="why">${sectionHead('BUILT FOR YOUR BUSINESS', '为电商团队而做', '让创意跟得上上新，<br>让素材接得住业务。', '把零散的制作环节，变成团队可复用的工作流程。')}<div class="editorial-three"><article><span class="index">01 / CREATE</span><h3>从一款商品，延展更多内容</h3><p>商品图、模特场景图、细节图与视频，围绕同一商品信息展开，减少反复准备素材。</p></article><article><span class="index">02 / COLLABORATE</span><h3>让好效果，变成团队的经验</h3><p>把商品素材、风格模板和任务结果集中管理。生成之后经过审核，再交到业务团队手里。</p></article><article><span class="index">03 / DELIVER</span><h3>从看见商品，到完成交付</h3><p>按需衔接活动入口、权益兑换与订单履约，让内容之后的业务也有系统承接。</p></article></div></section>
<section class="section showcase-section" id="showcase"><div class="container">${sectionHead('A PRODUCT, REIMAGINED', '真实素材展示', '同一个商品，<br>打开更多表达。', '以绿色家居服为例，看看商品细节、模特场景和视频如何连接。')}<div class="showcase-grid"><figure class="showcase-detail">${imageButton('detail', '绿色家居服 · 商品细节素材')}<figcaption><span>01 — 商品细节</span><small>从颜色、图案与版型出发</small></figcaption></figure><figure>${imageButton('scene', '绿色家居服 · 模特场景素材')}<figcaption><span>02 — 场景表达</span><small>让商品进入真实的使用想象</small></figcaption></figure><figure class="showcase-video"><button class="image-open" data-video="/assets/video-result-web.mp4" data-poster="/assets/video-poster.webp" data-caption="授权参考视频复刻 · 绿色家居服" aria-label="播放视频复刻结果">${picture('video-poster', '绿色家居服视频结果')}<span class="play-circle">▶</span><span class="video-tag">AI VIDEO</span></button><figcaption><span>03 — 视频延展</span><small>基于授权参考视频复刻</small></figcaption></figure></div><div class="section-tail"><p>以上为素材展示，实际产出需结合商品特征与审核要求确认。</p><a class="text-link" href="/aigc.html#showcase">探索素材工作台 ${arrow}</a></div></div></section>
<section class="section container workbench-section">${sectionHead('YOUR CREATIVE WORKBENCH', 'AIGC 素材工作台', '好素材背后，<br>是一套好用的工作方式。', '商品、模板、图片、视频与创作任务，在一个工作台里衔接。')}<div class="workflow-strip"><span><b>01</b> 准备商品素材</span><i>→</i><span><b>02</b> 选择模板与创作</span><i>→</i><span><b>03</b> 图片 / 视频生成</span><i>→</i><span><b>04</b> 审核与归档</span></div><div class="browser-frame"><div class="browser-top"><span><i></i><i></i><i></i></span><span>礼链 · AIGC 素材工作台</span><span>PRODUCT VIEW</span></div>${imageButton('workbench', 'AIGC 素材工作台实机截图，界面中保留达芬奇密码产品名称')}</div><div class="section-tail"><p>现有工作台界面 · 产品内名称为「达芬奇密码」</p><a class="text-link" href="/aigc.html">了解完整工作流程 ${arrow}</a></div></section>
<section class="matrix-section"><div class="container matrix-layout"><div>${eyebrow('CONNECTED COMMERCE', '礼链解决方案')}<h2>从素材起步，<br>向业务延伸。</h2><p>以成熟的内容生产与履约能力为基础，<br>围绕你的实际业务，组合适合的服务。</p><a class="button light" href="/solutions.html">了解电商解决方案 ${arrow}</a></div><div class="matrix-list"><a href="/aigc.html"><span>01</span><div><h3>AIGC 内容生产</h3><p>商品素材 · 图片视频 · 模板复用</p></div><span class="matrix-state">核心产品 ↗</span></a><a href="/solutions.html#fulfillment"><span>02</span><div><h3>电商履约交付</h3><p>活动承接 · 权益兑换 · 订单履约</p></div><span class="matrix-state">成熟方案 ↗</span></a><a href="/solutions.html#extension"><span>03</span><div><h3>AI 运营辅助</h3><p>活动策划 · 内容文案 · 复盘辅助</p></div><span class="matrix-state muted">按需评估 ↗</span></a><a href="/solutions.html#extension"><span>04</span><div><h3>独立站与获客</h3><p>品牌展示 · 线索承接 · 渠道推广</p></div><span class="matrix-state muted">定制咨询 ↗</span></a></div></div></section>
<section class="section container">${sectionHead('A WAY THAT FITS YOU', '合作方式', '标准产品打底，<br>你的业务决定下一步。')}<div class="service-pair"><article><span class="index">PRODUCT / 标准产品</span><h3>把成熟能力用起来</h3><p>从 AIGC 素材工作台或履约系统开始，通过产品演示了解功能，再确认适用场景与使用方式。</p><a class="text-link" href="/aigc.html">了解产品 ${arrow}</a></article><article><span class="index">SERVICE / 定制服务</span><h3>把业务需求落下去</h3><p>围绕你的业务流程、系统对接和专属场景，确认需求、交付范围与验收方式。</p><button class="text-link" data-inquiry>聊聊定制需求 ${arrow}</button></article></div></section>
<section class="partner-teaser container"><div class="partner-emblem" aria-hidden="true">L<span>PARTNERS</span></div><div><p class="eyebrow">GROW TOGETHER</p><h2>把本地的信任，<br>连接到新的生意。</h2><p>你推荐客户，我们负责产品、成交与交付。<br>欢迎成为礼链城市合伙人。</p></div><a class="button primary" href="/partners.html">了解合伙人计划 ${arrow}</a></section>${cta()}`;

const aigc = `<section class="page-hero container">${eyebrow('AIGC WORKBENCH', '礼链素材工作台')}<div class="page-hero-row"><h1>商品一上新，<br><span class="serif-accent">图片视频一起做。</span></h1><div><p>把商品事实、创作模板、图片视频和审核归档连接起来，让内容生产成为团队可复用的能力。</p>${button()}</div></div></section>
<section class="container product-wide"><div class="browser-frame"><div class="browser-top"><span><i></i><i></i><i></i></span><span>礼链 AIGC 素材工作台 · 实机界面</span><span>WORKBENCH</span></div>${imageButton('workbench', '素材工作台首页实机界面')}</div><p class="caption-note">现有产品界面中使用「达芬奇密码」名称，由礼链提供产品与落地服务。</p></section>
<section class="section container" id="showcase">${sectionHead('SEE WHAT’S POSSIBLE', '效果与过程', '先看效果，再聊你的商品。', '当前以服装实机素材展示能力；其他品类可结合你的商品样本沟通评估。')}<div class="filter-bar" role="group" aria-label="筛选素材"><button class="filter active" data-filter="all" aria-pressed="true">全部素材</button><button class="filter" data-filter="image" aria-pressed="false">图片素材</button><button class="filter" data-filter="video" aria-pressed="false">视频素材</button></div><div class="case-grid"><figure data-category="image">${imageButton('scene', '绿色家居服 · 模特场景素材')}<figcaption><h3>模特场景图</h3><p>让商品进入可感知的生活场景</p></figcaption></figure><figure data-category="image" class="case-detail">${imageButton('detail', '绿色家居服 · 商品细节素材')}<figcaption><h3>商品细节</h3><p>围绕面料、图案与版型准备素材</p></figcaption></figure><figure data-category="video"><button class="image-open" data-video="/assets/video-reference-web.mp4" data-poster="/assets/reference-poster.webp" data-caption="授权参考视频" aria-label="播放授权参考视频">${picture('reference-poster', '授权参考视频画面')}<span class="play-circle">▶</span></button><figcaption><h3>授权参考视频</h3><p>参考镜头表达与节奏</p></figcaption></figure><figure data-category="video"><button class="image-open" data-video="/assets/video-result-web.mp4" data-poster="/assets/video-poster.webp" data-caption="绿色家居服 · 授权参考视频复刻结果" aria-label="播放复刻结果">${picture('video-poster', '绿色家居服视频复刻画面')}<span class="play-circle">▶</span></button><figcaption><h3>视频复刻结果</h3><p>围绕商品延展视频表达</p></figcaption></figure></div><p class="caption-note">素材效果需经过人工审核。图片与视频示例不代表每次生成均能达到相同效果。</p></section>
<section class="section capability-section"><div class="container">${sectionHead('FROM ASSETS TO OUTPUT', '产品能力', '让每一步创作，<br>都有下一步。')}<div class="capability-tabs" role="tablist" aria-label="工作台能力">${[['product-management','商品素材管理'],['image-production','图片素材生产'],['video-production','视频素材生产'],['creation','AI 自由创作']].map(([key,label],i)=>`<button role="tab" id="tab-${key}" aria-controls="panel-${key}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-tab="${key}"><span>0${i+1}</span>${label}</button>`).join('')}</div>${[
['product-management','以商品信息为起点','集中管理商品、SKU 与主体素材，为每次创作准备清楚的商品信息。需要 ERP 对接时，单独确认接口范围与交付方式。'],
['image-production','按业务目标，组织图片生产','主图、场景图、细节图与上身 / 三视图，围绕用途创建任务。保留结果与任务记录，便于审核、调整和复用。'],
['video-production','让图片，延展成动态内容','支持首帧视频创作，以及基于授权参考视频的镜头与节奏复刻。实际效果结合商品、动作和镜头复杂度评估。'],
['creation','给创意，留一点自由','引用已有素材，多轮调整创作方向；将满意的结果继续创作或归档，让探索和生产自然衔接。']
].map(([key,title,desc],i)=>`<div class="capability-panel" role="tabpanel" id="panel-${key}" aria-labelledby="tab-${key}" tabindex="0" ${i?'hidden':''}><div><h3>${title}</h3><p>${desc}</p>${button('预约工作台演示')}</div>${imageButton(key,title+' · 实机截图')}</div>`).join('')}</div></section>
<section class="section container">${sectionHead('DESIGNED FOR COMMERCE', '面向全品类电商', '从你的场景出发，<br>找到合适的用法。')}<div class="industry-list"><div><span>01</span><h3>服装与配饰</h3><p>模特上身、场景表达、商品细节与短视频</p></div><div><span>02</span><h3>美妆与个护</h3><p>产品展示与场景素材，按商品样本评估</p></div><div><span>03</span><h3>家居与生活</h3><p>空间场景、商品陈列与活动视觉</p></div><div><span>04</span><h3>礼品与福利</h3><p>活动素材、品牌表达与兑换履约衔接</p></div></div></section><section class="section container faq-section"><h2>你可能还想知道</h2>${faq([
['这是软件，还是素材代做服务？','礼链提供标准产品与定制服务。你可以先了解素材工作台，再根据团队情况沟通部署、使用与落地支持；具体交付范围在合作前确认。'],
['可以自动发布到电商平台吗？','当前官网展示的是素材生产与管理能力。自动多平台发布不作为已上线能力承诺，系统对接需求可单独评估。'],
['生成的素材可以直接使用吗？','上线前需要由业务团队审核商品颜色、版型、图案、文案与使用要求。我们会结合你的场景确认审核标准和使用边界。'],
['如何了解价格和定制范围？','先告诉我们品类、素材需求和团队工作方式。我们通过产品演示与需求沟通，确认标准产品是否适用，以及需要哪些定制服务。']])}</section>${cta()}`;

function faq(items) {return `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`;}
const solutions = `<section class="page-hero container">${eyebrow('LILIAN SOLUTIONS', '电商解决方案')}<div class="page-hero-row"><h1>内容的下一步，<br><span class="serif-accent">是业务的每一步。</span></h1><div><p>从商品内容生产，到活动承接与订单履约。用标准产品打底，再按业务需要组合服务。</p>${button('咨询我的业务场景')}</div></div></section>
<section class="container solution-overview">${imageButton('matrix','礼链 AI 电商增长智能体矩阵 · 解决方案全景')}<p class="caption-note">业务全景示意。AIGC 与履约为成熟能力；运营辅助、独立站与获客按实际需求评估，不代表所有模块已自动打通。</p></section>
<section class="section container solution-feature"><div>${eyebrow('01 / CONTENT', '内容生产')}<h2>给每一款商品，<br>更丰富的表达。</h2><p>用 AIGC 素材工作台集中组织商品、模板和创作任务，生成图片与视频，经过审核后归档使用。</p><ul class="check-list"><li>商品主体素材与 SKU 管理</li><li>商品图、场景图、细节图与视频</li><li>模板复用、任务记录与审核归档</li></ul><a class="text-link" href="/aigc.html">了解 AIGC 素材工作台 ${arrow}</a></div>${imageButton('image-production','AIGC 图片素材生产工作台')}</section>
<section class="fulfillment-section" id="fulfillment"><div class="container solution-feature"><div>${eyebrow('02 / FULFILLMENT', '活动与履约')}<h2>从活动入口，<br>到礼品送达。</h2><p>为礼品服务商、企业福利与会员活动提供系统承接，让权益兑换与订单履约有序进行。</p><ul class="check-list"><li>活动与兑换入口、礼包及兑换码管理</li><li>移动商城、商品选择与收货信息</li><li>订单管理、物流跟踪与活动复盘</li></ul>${button('咨询履约方案')}</div>${imageButton('fulfillment','礼链履约系统 · 管理后台与移动商城展示')}</div></section>
<section class="section container" id="extension">${sectionHead('EXTEND WHEN YOU NEED', '按需延伸', '围绕你的业务，<br>多走一步。', '以下方向通过需求沟通确认适用性、交付范围和实施方式。')}<div class="service-pair"><article><span class="index">OPERATIONS / 运营辅助</span><h3>让运营准备更有条理</h3><p>围绕活动方案、商品卖点、运营文案和复盘报告，评估 AI 辅助的适用环节。业务决策与执行确认仍由团队负责。</p><button class="text-link" data-inquiry>沟通运营需求 ${arrow}</button></article><article><span class="index">ACQUISITION / 独立站与获客</span><h3>给品牌一个清晰的入口</h3><p>结合品牌展示、商品介绍和线索承接需求，沟通独立站与渠道推广页面。推广效果不作保证性承诺。</p><button class="text-link" data-inquiry>沟通建站需求 ${arrow}</button></article></div></section>
<section class="section services-section" id="services"><div class="container">${sectionHead('PRODUCT + SERVICE', '交付方式', '先把需求说清，<br>再把事情做好。')}<ol class="delivery-steps"><li><span>01</span><h3>了解业务</h3><p>沟通品类、现有流程和最想解决的问题。</p></li><li><span>02</span><h3>演示与评估</h3><p>看标准产品，确认哪些能力适合你。</p></li><li><span>03</span><h3>确认合作</h3><p>约定产品、定制范围、报价和验收方式。</p></li><li><span>04</span><h3>实施与交付</h3><p>按约定完成实施、验证与使用沟通。</p></li></ol></div></section>${cta()}`;

const partners = `<section class="partner-hero"><div class="container"><div>${eyebrow('LILIAN CITY PARTNERS', '礼链城市合伙人')}<h1>你连接本地信任，<br><span class="serif-accent">我们一起创造价值。</span></h1><p>把你熟悉的企业，连接到适合的 AI 产品。<br>你推荐客户，礼链负责产品、成交与交付。</p><a class="button light" href="#apply">申请成为城市合伙人 ${arrow}</a></div><div class="partner-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="orbit-label label-one">LOCAL CONNECTION</span><span class="orbit-label label-two">SHARED GROWTH</span><div class="seal"><span>LILIAN</span><strong>共生<br>共长</strong><small>CITY PARTNERS</small></div><i class="orbit-point point-one"></i><i class="orbit-point point-two"></i></div></div></section>
<section class="section container">${sectionHead('WHO WE WORK WITH', '适合谁加入', '让你已有的连接，<br>拥有新的可能。')}<div class="editorial-three"><article><span class="index">01</span><h3>电商与企业服务伙伴</h3><p>熟悉电商团队的运营需求，愿意推荐合适的产品与服务。</p></article><article><span class="index">02</span><h3>礼品与福利服务商</h3><p>有企业客户资源，希望进一步沟通 AI 内容与数字化履约方案。</p></article><article><span class="index">03</span><h3>本地渠道与行业连接者</h3><p>了解当地企业，有真实的业务连接与长期合作意愿。</p></article></div></section>
<section class="responsibility-section"><div class="container responsibility-grid"><div><p class="eyebrow">YOUR PART</p><h2>你熟悉客户，<br>也了解当地的生意。</h2><p>发现适合的需求、推荐客户、协助建立沟通。<br>发挥你的本地资源与信任优势。</p></div><div><p class="eyebrow">OUR PART</p><h2>我们理解产品，<br>也负责把方案交付。</h2><p>由礼链负责产品演示、需求评估、报价签约与实施交付，与你一起推进真实合作。</p></div></div></section>
<section class="section container"><div class="partner-process"><div>${eyebrow('THE FIRST STEP', '如何开始')}<h2>先认识，<br>再一起做事。</h2><p>具体合作权益、授权范围与收益规则，<br>在双方沟通后单独约定。</p></div><ol><li><span>01</span><div><h3>提交合作申请</h3><p>告诉我们所在城市与客户资源。</p></div></li><li><span>02</span><div><h3>沟通合作方式</h3><p>了解彼此，明确适合的客户与协作方式。</p></div></li><li><span>03</span><div><h3>确认合作关系</h3><p>确认职责与权益，开始推进客户合作。</p></div></li></ol></div></section>
<section class="application-section" id="apply"><div class="container application-layout"><div>${eyebrow('LET’S BUILD TOGETHER', '提交申请')}<h2>下一站，<br>就在你的城市。</h2><p>填下这些信息，我们从一次沟通开始。</p><div class="application-note"><span>也可以先聊聊</span><button class="text-link" data-wechat>扫码联系礼链 ${arrow}</button></div></div><div class="form-card"><h3>城市合伙人申请</h3>${leadForm('partner','partner')}</div></div></section>`;
const contact = `<section class="page-hero container">${eyebrow('HELLO, WE ARE LILIAN', '关于礼链')}<div class="page-hero-row"><h1>让 AI，<br><span class="serif-accent">走进真实的生意。</span></h1><div><p>礼链由杭州礼鲤科技有限公司提供产品与服务，围绕电商素材生产、活动承接和履约交付，帮助团队把 AI 用到具体的工作中。</p><p>我们提供标准产品，也围绕业务需求开展定制服务。</p></div></div></section><section class="contact-section"><div class="container application-layout"><div>${eyebrow('START A CONVERSATION', '联系我们')}<h2>先聊聊，<br>你想完成的事。</h2><p>准备了解产品、沟通定制需求，<br>或探讨合作，都可以从这里开始。</p><div class="inline-qr"><img src="/assets/contact-qr.png" width="132" height="132" alt="礼链业务联系二维码"><div><h3>微信扫码联系</h3><p>无需填写表单，也能直接聊</p><button class="text-link" data-wechat>查看 / 保存二维码 ${arrow}</button></div></div><a class="text-link" href="/partners.html">我是渠道伙伴，想申请合作 ${arrow}</a></div><div class="form-card"><h3>预约产品演示 / 咨询方案</h3>${leadForm('lead','contact')}</div></div></section>`;
const privacy = `<section class="container privacy-page"><p class="eyebrow">PRIVACY NOTICE</p><h1>隐私说明</h1><p class="caption-note">更新日期：2026 年 9 月 8 日</p><p>杭州礼鲤科技有限公司（以下简称“礼链”）通过本网站接收产品咨询与城市合伙人申请。本说明解释我们收集哪些信息，以及如何使用这些信息。</p><h2>我们收集什么信息</h2><p>产品咨询包含手机号、公司名称，以及你选择提供的称呼、感兴趣的方案和需求描述。合伙人申请还包含姓名、意向城市，以及你选择填写的客户资源与合作说明。系统同时记录提交时间、来源页面、提交标识和同意联系的状态。</p><h2>信息如何使用与保存</h2><p>信息用于回复你的咨询、安排产品演示、评估合作需求和记录跟进情况。提交的信息保存在礼链使用的飞书多维表格中，由有业务需要的工作人员处理。我们不会在官网公开你的手机号或申请信息，也不会将这些信息作为公开案例发布。</p><h2>安全与必要的技术处理</h2><p>网站服务端会校验表单并暂时处理网络地址等必要信息，用于限制异常请求和避免重复提交。网站不会把手机号、公司名称或需求内容发送到流量统计事件中。浏览器仅在当前页面会话中保留提交标识，用于失败重试。</p><h2>你可以如何选择</h2><p>你可以不提交表单，直接通过页面上的二维码联系我们。表单需要你主动勾选同意联系后才提交。如需查询、更正或请求删除已提交的信息，或撤回后续业务联系意愿，请通过官网的业务联系二维码提出，我们将在核实后处理。信息仅在业务联系所需期限内保存，业务结束后定期复核保留必要性。</p><h2>第三方服务</h2><p>表单存储使用飞书服务；扫码联系将进入微信或企业微信的服务环境，相应服务适用其自身的隐私规则。你可以在进入这些服务前决定是否继续。</p><a class="button primary" href="/contact.html">联系礼链 ${arrow}</a></section>`;

const pages = [
['index.html','home','礼链 · AI 电商解决方案｜AIGC 素材工作台','礼链为全品类电商团队提供 AIGC 素材工作台、电商履约与定制服务。从商品图片和视频生产，到活动承接和订单履约。',home],
['aigc.html','aigc','AIGC 素材工作台｜礼链','了解礼链 AIGC 素材工作台的商品管理、图片生产、视频创作与素材归档，查看真实素材与工作台演示。',aigc],
['solutions.html','solutions','电商解决方案｜礼链','从 AI 内容生产到活动承接、权益兑换与订单履约，以标准产品和定制服务支持电商业务。',solutions],
['partners.html','partners','城市合伙人计划｜礼链','成为礼链城市合伙人。你推荐客户，礼链负责产品、成交与交付。提交城市合作申请。',partners],
['contact.html','contact','关于与联系｜礼链','联系杭州礼鲤科技有限公司，预约 AIGC 素材工作台演示，咨询标准产品、定制服务与渠道合作。',contact],
['privacy.html','privacy','隐私说明｜礼链','了解礼链官网产品咨询和城市合伙人申请的信息收集、使用与联系选择。',privacy]
];
for(const [file,key,title,description,body] of pages){
 const url=`https://www.lilianagent.cn/${file==='index.html'?'':file}`;
 const html=`<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta name="theme-color" content="#123e35"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="zh_CN"><meta property="og:site_name" content="礼链"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://www.lilianagent.cn/assets/share.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/brand.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css?v=${assetVersion}"><script src="/assets/site.js?v=${assetVersion}" defer></script></head><body data-page="${key}">${nav(key)}<main id="main">${body}</main>${footer()}${dialogs()}<noscript><div class="noscript-note">表单提交与素材预览需要启用 JavaScript。你仍可在<a href="/contact.html">联系页</a>扫描二维码联系礼链。</div></noscript></body></html>`;
 await writeFile(new URL(file,output),html);
}
await writeFile(new URL('sitemap.xml',output),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(([file])=>`<url><loc>https://www.lilianagent.cn/${file==='index.html'?'':file}</loc></url>`).join('')}</urlset>\n`);
console.log(`Generated ${pages.length} pages in ${fileURLToPath(output)}`);
