import { videoWorkbench } from './video-workbench.mjs';
export const trialMarkup = `<section class="section trial-section" id="trial" aria-labelledby="trial-title"><div class="container">
<div class="trial-heading"><div><p class="eyebrow">TRY IT WITH YOUR PRODUCT</p><h2 id="trial-title">下一组场景，<br>从你的商品开始。</h2><p>一张白底图，一套预设模板。把复杂的配置，留给我们。</p></div><span class="trial-benefit">首次注册 · 3 次场景组图体验</span></div>
<div class="trial-shell"><div class="trial-bar"><strong>礼链 · 轻量体验工作台</strong><span id="trial-balance">登录后开放</span><button class="text-button" id="trial-exit" hidden>退出演示</button></div>
<div class="trial-template-preview"><button class="trial-template-image" data-image="/assets/trial-template-preview.webp" data-caption="试用模板效果示例：窗边自然光家居服；右下角为该示例的商品输入，非本次生成结果" aria-label="放大查看试用模板效果"><img src="/assets/trial-template-preview.webp" alt="窗边自然光家居服模板效果，右下角展示该案例的白底商品输入" loading="lazy"><span aria-hidden="true">查看大图 ↗</span></button><div><p class="eyebrow">TEMPLATE PREVIEW / 模板效果</p><h3>先看看，你的商品将如何被呈现。</h3><p>窗边自然光，轻松的家居氛围。<br>上传商品白底图，按已选好的模板体验场景组图。</p><span class="trial-template-tag">当前预设 · 无需选择或配置</span><p class="trial-small">示例右下角是对应商品输入，大图展示模板效果。<br>这是风格参考，不是你上传商品的生成结果。</p></div></div>
<div id="trial-locked" class="trial-locked"><div class="locked-illustration" aria-hidden="true"><span>白底商品图</span><b>→</b><span>场景组图</span></div><div class="lock-symbol" aria-hidden="true">▣</div><h3>解锁你的商品体验</h3><p>手机号注册 / 登录后，即可上传白底商品图。<br>企业信息可选填，无需配置提示词或模板。</p><button class="button primary" id="trial-login">立即体验 ↗</button><p class="trial-small">在线试用接入中，手机号验证后开放。</p></div>
<div id="trial-workspace" hidden><p class="trial-demo-banner" role="status">本地前端演示 · 不创建账号、不发送短信、不上传图片；结果为固定案例，不是你的商品生成结果。</p><div class="trial-mode" role="group" aria-label="选择体验类型"><button class="filter active" id="trial-image-mode" aria-pressed="true">场景组图</button><button class="filter" id="trial-video-mode" aria-pressed="false">视频演示</button></div><div id="trial-image-pane"><div class="trial-work-grid"><div><label class="trial-upload" for="trial-file"><span id="trial-upload-label">＋<br>上传一张白底商品图<small>JPG / PNG / WebP，最大 10MB</small></span><img id="trial-upload-preview" alt="你选择的商品图预览" hidden><input type="file" id="trial-file" accept="image/jpeg,image/png,image/webp"></label><p class="trial-small">使用已选好的场景模板，无需其他设置。</p><button class="button primary" id="trial-generate" disabled>查看场景组图演示 ↗</button><p class="trial-small" id="trial-status" role="status" aria-live="polite"></p></div><div class="trial-output" id="trial-output"><div id="trial-empty"><span class="trial-output-icon">↗</span><h3>你的下一组商品场景</h3><p>选择白底图后，查看场景组图的呈现方式。</p></div><div id="trial-results" hidden><p class="eyebrow">固定案例 · 非实时生成</p><img src="/assets/trial-template-preview.webp" alt="当前模板的固定效果示例，非用户图片生成结果" loading="lazy"><p class="trial-small">真实结果数量由后台试用模板决定。</p></div></div></div></div><div id="trial-video-pane" hidden>${videoWorkbench('trial')}</div><div class="trial-after"><p>想把模板、视频与素材管理用到团队里？</p><button class="text-link" data-inquiry>联系礼链，开通完整产品 ↗</button></div></div>
</div><button class="trial-local-preview text-link" id="trial-demo" hidden>本地验收：查看登录后界面（不创建账号） ↗</button>
</div></section>
<dialog id="trial-auth" class="form-dialog trial-auth" aria-labelledby="trial-auth-title"><button class="dialog-close" data-close aria-label="关闭试用登录">×</button><p class="eyebrow">START WITH ONE PRODUCT</p><h2 id="trial-auth-title">先登录，再看效果。</h2><p class="dialog-intro">新用户首次注册，获得 3 次场景组图体验。</p><form id="trial-auth-form"><label for="trial-phone">手机号<input id="trial-phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="11" placeholder="请输入中国大陆手机号" required pattern="1[3-9][0-9]{9}"></label><label for="trial-code">短信验证码</label><div class="trial-code-row"><input id="trial-code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="请输入验证码" required pattern="[0-9]{6}"><button type="button" class="button secondary" id="trial-send">获取验证码</button></div><p class="trial-small">验证通过后可选择企业，也可以跳过。</p><label class="consent"><input type="checkbox" required><span>我已阅读<a href="/privacy.html" target="_blank" rel="noopener">隐私说明</a>。注册规则将在试用正式开放时提供。</span></label><p id="trial-auth-status" class="form-status" role="status"></p><button class="button primary" type="submit">登录 / 注册</button></form></dialog>
<dialog id="trial-company" class="form-dialog trial-auth" aria-labelledby="trial-company-title"><button class="dialog-close" data-close aria-label="关闭企业选择">×</button><p class="eyebrow">OPTIONAL</p><h2 id="trial-company-title">让我们了解你的企业。</h2><p class="dialog-intro">企业信息选填，暂时跳过也能继续体验。</p><label for="trial-company-query">企业名称<input id="trial-company-query" placeholder="输入企业名称搜索" maxlength="100" autocomplete="organization"></label><p class="form-status" id="trial-company-status" role="status">企业查询待接入。本地演示不会保存企业信息。</p><button class="button primary" id="trial-company-skip">暂时跳过，进入演示 ↗</button></dialog>`;
